from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
import yaml
import uuid
import time
from automation.domain.exceptions import DSLValidationError


class WorkflowMeta(BaseModel):
    version: str = "1.0"
    generated_at: float = Field(default_factory=time.time)
    generator: str = "automation-dsl-builder"


class NodeBlueprint(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    type: str
    title: str
    data: Dict[str, Any] = {}
    position: Dict[str, float] = {"x": 0, "y": 0}


class EdgeBlueprint(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    source: str
    target: str
    source_handle: str = "source"
    target_handle: str = "target"


class WorkflowBlueprint(BaseModel):
    meta: WorkflowMeta = Field(default_factory=WorkflowMeta)
    nodes: List[NodeBlueprint] = []
    edges: List[EdgeBlueprint] = []
    app: Dict[str, Any] = {}


class DSLBuilder:
    def __init__(
        self,
        app_name: str = "Automated App",
        mode: str = "workflow"
    ):
        self.blueprint = WorkflowBlueprint()
        self.blueprint.app = {
            "name": app_name,
            "mode": mode,
            "icon": "🤖",
            "icon_background": "#FFEAD5",
            "description": "Generated by Dify Automation"
        }

    def add_node(
        self,
        type: str,
        title: str,
        data: Dict[str, Any] = {},
        position: Optional[Dict[str, float]] = None
    ) -> str:
        if position is None:
            # Simple auto-layout: stack vertically
            y = len(self.blueprint.nodes) * 150
            position = {"x": 0, "y": y}

        node = NodeBlueprint(
            type=type, title=title, data=data, position=position
        )
        self.blueprint.nodes.append(node)
        return node.id

    def add_edge(self, source_id: str, target_id: str):
        edge = EdgeBlueprint(source=source_id, target=target_id)
        self.blueprint.edges.append(edge)

    def add_start_node(self, variables: List[Dict[str, Any]]) -> str:
        """
        Add a start node.
        variables example:
        [{"variable": "query", "label": "Query", "type": "text-input"}]
        """
        return self.add_node("start", "Start", {"variables": variables})

    def add_end_node(self, outputs: List[Dict[str, Any]]) -> str:
        """
        Add an end node.
        outputs example:
        [{"variable": "text", "value_selector": ["llm_node_id", "text"]}]
        """
        return self.add_node("end", "End", {"outputs": outputs})

    def add_llm_node(
        self,
        title: str,
        prompt_template: List[Dict[str, Any]],
        model_config: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Add an LLM node.
        prompt_template: [{"role": "user", "text": "{{#query#}}"}]
        """
        if model_config is None:
            model_config = {
                "provider": "openai",
                "name": "gpt-3.5-turbo",
                "mode": "chat",
                "completion_params": {"temperature": 0.7}
            }

        data = {
            "model": model_config,
            "prompt_template": prompt_template,
            "context": {"enabled": False},
            "vision": {"enabled": False}
        }
        return self.add_node("llm", title, data)

    def add_code_node(
        self,
        title: str,
        code: str,
        variables: List[Dict[str, Any]],
        outputs: Dict[str, Any]
    ) -> str:
        """
        Add a Code node.
        """
        data = {
            "code": code,
            "code_language": "python3",
            "variables": variables,
            "outputs": outputs
        }
        return self.add_node("code", title, data)

    def validate(self):
        """
        Validate the workflow structure.
        """
        node_types = [n.type for n in self.blueprint.nodes]
        if "start" not in node_types:
            raise DSLValidationError("Workflow must have a 'start' node")
        if "end" not in node_types:
            raise DSLValidationError("Workflow must have an 'end' node")

        # Check for disconnected nodes (basic check)
        if len(self.blueprint.nodes) > 1:
            connected_nodes = set()
            for edge in self.blueprint.edges:
                connected_nodes.add(edge.source)
                connected_nodes.add(edge.target)

            if len(connected_nodes) < len(self.blueprint.nodes):
                # This is a weak check because it doesn't check connectivity
                # graph, just that every node has at least one edge.
                pass

    def to_dict(self) -> Dict[str, Any]:
        self.validate()

        nodes_data = []
        for node in self.blueprint.nodes:
            node_data: Dict[str, Any] = {
                "title": node.title,
                "type": node.type,
                **node.data
            }
            # Ensure internal type is set
            node_data["type"] = node.type

            node_dict = {
                "id": node.id,
                "data": node_data,
                "position": node.position,
                "type": "custom",
            }
            nodes_data.append(node_dict)

        edges_data = []
        for edge in self.blueprint.edges:
            edges_data.append({
                "id": edge.id,
                "source": edge.source,
                "target": edge.target,
                "sourceHandle": edge.source_handle,
                "targetHandle": edge.target_handle,
                "type": "button"
            })

        return {
            "app": self.blueprint.app,
            "workflow": {
                "graph": {
                    "nodes": nodes_data,
                    "edges": edges_data,
                    "viewport": {"x": 0, "y": 0, "zoom": 1}
                },
                "features": {
                    "opening_statement": "",
                    "suggested_questions": [],
                    "speech_to_text": {"enabled": False},
                    "text_to_speech": {"enabled": False},
                    "file_upload": {"image": {"enabled": False}}
                },
                "environment_variables": [],
                "conversation_variables": []
            },
            "kind": "app",
            "version": "0.1.0"  # Dify DSL version
        }

    def to_yaml(self) -> str:
        return yaml.dump(self.to_dict(), sort_keys=False, allow_unicode=True)
